spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=file:///C:/Users/abhimanyu.a.yadav/Desktop/travel-fleet-management/backend/config-repo
spring.cloud.config.server.git.default-label=main